[worker]
data_dir = "/tmp"
instance_type = "small"

[avs]
# for mainnet, use:
gateway_url = "ws://gateway.prod-distributed-query.prod.distributed-query.io:80"
issuer = "lagrange"
#This is a display name for your worker. please change it.
worker_id = "CHANGE_ME"

[prometheus]
port = 9090
